/// <reference types="vite/client" />
import { app, BrowserWindow, ipcMain, net, Tray, Menu, Notification, globalShortcut, nativeImage } from 'electron'
import { autoUpdater } from 'electron-updater'
import path from 'path'
import fs from 'fs'
import { spawn } from 'child_process'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

let mainWindow: BrowserWindow | null = null
let rpc: any = null
let rpcReady = false
let rpcReconnectTimer: ReturnType<typeof setTimeout> | null = null
let rpcStartTime: number | null = null
let downloadedUpdatePath: string | null = null
let isQuitting = false

const CLIENT_ID = import.meta.env.VITE_DISCORD_CLIENT_ID || process.env.VITE_DISCORD_CLIENT_ID || '1337133713371337'

autoUpdater.autoDownload = true
autoUpdater.autoInstallOnAppQuit = true
// electron-updater reads publish config from package.json (github provider)
// latest.yml is generated by electron-builder automatically

const isDev = !app.isPackaged

const WAVEIFY_SCHEME = 'waveify'
let pendingSongId: string | null = null

function extractSongIdFromUrl(url: string): string | null {
  const match = url.match(/^waveify:\/\/song\/([0-9a-fA-F-]{36})/i)
  return match ? match[1] : null
}

function extractSongIdFromArgv(argv: string[]): string | null {
  const url = argv.find((a) => a.startsWith('waveify://'))
  return url ? extractSongIdFromUrl(url) : null
}

function queueSongId(songId: string) {
  pendingSongId = songId
  if (mainWindow && !mainWindow.webContents.isLoading()) {
    mainWindow.webContents.send('deep-link:song', songId)
    pendingSongId = null
  }
}

ipcMain.on('deep-link:ready', () => {
  if (pendingSongId && mainWindow && !mainWindow.webContents.isLoading()) {
    mainWindow.webContents.send('deep-link:song', pendingSongId)
    pendingSongId = null
  }
})

// Single instance: deep link launches go to the running instance
if (!app.requestSingleInstanceLock()) {
  app.quit()
}

if (process.defaultApp) {
  if (process.argv.length >= 2) {
    app.setAsDefaultProtocolClient(WAVEIFY_SCHEME, process.execPath, [path.resolve(process.argv[1])])
  }
} else {
  app.setAsDefaultProtocolClient(WAVEIFY_SCHEME)
}

app.on('second-instance', (_event, argv) => {
  if (mainWindow) {
    if (mainWindow.isMinimized()) mainWindow.restore()
    mainWindow.show()
    mainWindow.focus()
  }
  const songId = extractSongIdFromArgv(argv)
  if (songId) queueSongId(songId)
})

app.on('open-url', (_event, url) => {
  const songId = extractSongIdFromUrl(url)
  if (songId) queueSongId(songId)
})

autoUpdater.on('checking-for-update', () => {
  mainWindow?.webContents.send('update:checking')
})

autoUpdater.on('update-available', (info) => {
  mainWindow?.webContents.send('update:available', info)
})

autoUpdater.on('update-not-available', () => {
  mainWindow?.webContents.send('update:not-available')
})

autoUpdater.on('download-progress', (progress) => {
  mainWindow?.webContents.send('update:progress', progress)
})

autoUpdater.on('update-downloaded', (info) => {
  try {
    const helper = (autoUpdater as any).downloadedUpdateHelper
    if (helper?.file) downloadedUpdatePath = helper.file
  } catch {}
  if (!downloadedUpdatePath && (info as any)?.downloadedFile) {
    downloadedUpdatePath = (info as any).downloadedFile
  }
  mainWindow?.webContents.send('update:downloaded')
})

autoUpdater.on('error', (err) => {
  if (isDev) return
  const msg = err.message || ''
  console.log('[AutoUpdate] Error:', msg)
  if (msg.includes('404') || msg.includes('ENOENT') || msg.includes('latest.yml')) {
    mainWindow?.webContents.send('update:not-available')
    return
  }
  mainWindow?.webContents.send('update:error', msg.includes('Cannot') || msg.includes('connect') ? 'Sunucuya bağlanılamadı' : msg.slice(0, 100))
})

ipcMain.handle('app:version', () => app.getVersion())

ipcMain.on('update:check', () => {
  if (isDev) return
  autoUpdater.checkForUpdates()
})

ipcMain.on('update:download', () => {
  autoUpdater.downloadUpdate()
})

function applyPortableUpdate() {
  const portableExe = process.env.PORTABLE_EXECUTABLE_FILE
  if (!portableExe || !downloadedUpdatePath || !fs.existsSync(downloadedUpdatePath)) return false
  try {
    const exeDir = path.dirname(portableExe)
    const exeName = path.basename(portableExe)
    const oldExe = path.join(exeDir, exeName)
    const oldExeBackup = path.join(exeDir, `${exeName}.bak`)
    const batPath = path.join(exeDir, `update-${Date.now()}.bat`)

    if (fs.existsSync(oldExeBackup)) fs.unlinkSync(oldExeBackup)
    fs.renameSync(oldExe, oldExeBackup)

    const batContent = `@echo off
:wait
tasklist /FI "PID eq ${process.pid}" 2>NUL | find /I /N "${process.pid}" >NUL
if not errorlevel 1 (
  timeout /t 1 /nobreak >NUL
  goto wait
)
copy /Y "${downloadedUpdatePath}" "${oldExe}" >NUL
start "" "${oldExe}"
del "%~f0"
`
    fs.writeFileSync(batPath, batContent)
    spawn(batPath, [], { detached: true, stdio: 'ignore', windowsHide: true }).unref()
    return true
  } catch (e) {
    console.error('[Update] portable replace error:', e)
    try {
      const oldExe = path.join(path.dirname(portableExe), path.basename(portableExe))
      const backup = oldExe + '.bak'
      if (fs.existsSync(backup) && !fs.existsSync(oldExe)) fs.renameSync(backup, oldExe)
    } catch {}
    return false
  }
}

ipcMain.on('update:install', () => {
  if (applyPortableUpdate()) {
    app.quit()
    return
  }
  autoUpdater.quitAndInstall()
})

// Auto-install on quit for portable
app.on('before-quit', (event) => {
  if (isQuitting) return
  if (!downloadedUpdatePath || !process.env.PORTABLE_EXECUTABLE_FILE) return
  isQuitting = true
  event.preventDefault()
  applyPortableUpdate()
  app.exit()
})

async function initDiscordRPC(retries = 3) {
  console.log('[RPC] initDiscordRPC called, CLIENT_ID:', CLIENT_ID)
  for (let i = 0; i < retries; i++) {
    try {
      rpcReady = false
      const { Client } = await import('@xhayper/discord-rpc')
      console.log('[RPC] Module loaded, creating client...')
      const client = new Client({ clientId: CLIENT_ID })
      client.on('ready', () => {
        console.log('[RPC] READY event received, user:', client.user?.username)
        rpc = client
        rpcReady = true
        if (rpcReconnectTimer) { clearTimeout(rpcReconnectTimer); rpcReconnectTimer = null }
        updateDiscordPresence(null, false)
      })
      client.on('disconnected', () => {
        console.log('[RPC] DISCONNECTED')
        rpcReady = false
        rpc = null
        rpcReconnectTimer = setTimeout(() => initDiscordRPC(3), 10000)
      })
      console.log('[RPC] Calling login()...')
      await client.login()
      console.log('[RPC] login() resolved successfully')
      return
    } catch (e) {
      console.log('[RPC] login() failed:', e)
      if (i < retries - 1) await new Promise(r => setTimeout(r, 2000 * (i + 1)))
    }
  }
  console.log('[RPC] All retries exhausted')
}

function updateDiscordPresence(data: { title?: string; artist?: string; coverUrl?: string; isPlaying?: boolean; currentTime?: number; duration?: number } | null, isPlayingFallback?: boolean) {
  if (!data) return
  const song = data.title && data.artist ? { title: data.title, artist: data.artist } : null
  const playState = data.isPlaying ?? isPlayingFallback ?? false
  const curTime = data.currentTime ?? 0
  const dur = data.duration ?? 0
  const coverUrl = data.coverUrl || ''
  if (!rpc || !rpcReady) { console.log('[RPC] skip update - not ready'); return }
  try {
    const details = song ? song.title : 'Idle'
    const state = song ? song.artist : 'Waveify'
    const largeText = song ? `${song.title} - ${song.artist}` : 'Waveify'
    if (playState) {
      rpcStartTime = rpcStartTime || Date.now()
    } else {
      rpcStartTime = null
    }
    rpc.user?.setActivity({
      details,
      state,
      largeImageKey: coverUrl || 'waveify_logo',
      largeImageText: largeText,
      smallImageKey: playState ? 'play' : 'pause',
      smallImageText: playState ? 'Playing' : 'Paused',
      startTimestamp: playState && song ? (rpcStartTime || Date.now()) : undefined,
      instance: false,
    })
  } catch (e) { console.log('[RPC] setActivity error:', e) }
}

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1200,
    height: 800,
    minWidth: 900,
    minHeight: 600,
    titleBarStyle: 'hiddenInset',
    frame: false,
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'),
      contextIsolation: true,
      nodeIntegration: false,
      backgroundThrottling: false,
    },
    backgroundColor: '#121216',
    show: false,
  })

  mainWindow.once('ready-to-show', () => {
    mainWindow?.show()
    mainWindow?.focus()
    if (!app.isPackaged) mainWindow?.webContents.openDevTools()
  })

  const devUrl = import.meta.env.VITE_DEV_SERVER_URL || process.env.VITE_DEV_SERVER_URL
  if (devUrl) {
    mainWindow.loadURL(devUrl)
  } else {
    mainWindow.loadFile(path.join(__dirname, '../dist/index.html'))
  }

  mainWindow.on('closed', () => {
    mainWindow = null
  })
}

let tray: Tray | null = null

function createTray() {
  const icon = nativeImage.createEmpty()
  tray = new Tray(icon)
  tray.setToolTip('Waveify')
  const ctx = Menu.buildFromTemplate([
    { label: 'Waveify\'i Göster', click: () => { mainWindow?.show(); mainWindow?.focus() } },
    { label: 'Çal/Duraklat', click: () => mainWindow?.webContents.send('global:play-pause') },
    { label: 'Sonraki', click: () => mainWindow?.webContents.send('global:next') },
    { label: 'Önceki', click: () => mainWindow?.webContents.send('global:prev') },
    { type: 'separator' },
    { label: 'Çıkış', click: () => { isQuitting = true; app.quit() } },
  ])
  tray.setContextMenu(ctx)
  tray.on('double-click', () => { mainWindow?.show(); mainWindow?.focus() })
}

function registerGlobalShortcuts() {
  globalShortcut.register('MediaPlayPause', () => {
    mainWindow?.webContents.send('global:play-pause')
  })
  globalShortcut.register('MediaNextTrack', () => {
    mainWindow?.webContents.send('global:next')
  })
  globalShortcut.register('MediaPreviousTrack', () => {
    mainWindow?.webContents.send('global:prev')
  })
}

ipcMain.on('notify:song', (_e, data: { title: string; artist: string }) => {
  const n = new Notification({ title: data.title, body: data.artist + ' — Waveify' })
  n.on('click', () => { mainWindow?.show(); mainWindow?.focus() })
  n.show()
})

app.whenReady().then(() => {
  createWindow()
  initDiscordRPC()
  createTray()
  registerGlobalShortcuts()
  const initialSongId = extractSongIdFromArgv(process.argv)
  if (initialSongId) queueSongId(initialSongId)
})

app.on('will-quit', () => {
  globalShortcut.unregisterAll()
})

app.on('window-all-closed', () => {
  if (rpcReconnectTimer) { clearTimeout(rpcReconnectTimer); rpcReconnectTimer = null }
  if (rpc) { try { rpc.destroy() } catch {} rpc = null }
  if (process.platform !== 'darwin') app.quit()
})

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) createWindow()
})

ipcMain.on('window:minimize', () => mainWindow?.minimize())
ipcMain.on('window:maximize', () => {
  if (mainWindow?.isMaximized()) mainWindow.unmaximize()
  else mainWindow?.maximize()
})
ipcMain.on('window:close', () => mainWindow?.close())

ipcMain.on('discord:update', (_e, data: { title?: string; artist?: string; coverUrl?: string; isPlaying?: boolean; currentTime?: number; duration?: number }) => {
  updateDiscordPresence(data)
})

// Offline mode: cache songs to local filesystem
const cacheDir = path.join(app.getPath('userData'), 'song-cache')
if (!fs.existsSync(cacheDir)) fs.mkdirSync(cacheDir, { recursive: true })

ipcMain.handle('cache:save', async (_e, songId: string, audioUrl: string) => {
  try {
    const res = await net.fetch(audioUrl)
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    const buffer = Buffer.from(await res.arrayBuffer())
    const songPath = path.join(cacheDir, `${songId}.mp3`)
    fs.writeFileSync(songPath, buffer)
    return { success: true, path: songPath }
  } catch (e: any) {
    return { success: false, error: e.message }
  }
})

ipcMain.handle('cache:get', async (_e, songId: string) => {
  const songPath = path.join(cacheDir, `${songId}.mp3`)
  if (fs.existsSync(songPath)) {
    const buffer = fs.readFileSync(songPath)
    return { cached: true, buffer, path: songPath }
  }
  return { cached: false }
})

ipcMain.handle('cache:remove', async (_e, songId: string) => {
  const songPath = path.join(cacheDir, `${songId}.mp3`)
  if (fs.existsSync(songPath)) fs.unlinkSync(songPath)
  return { success: true }
})

ipcMain.handle('cache:list', async () => {
  const files = fs.readdirSync(cacheDir).filter(f => f.endsWith('.mp3'))
  return files.map(f => f.replace('.mp3', ''))
})

ipcMain.handle('cache:clear', async () => {
  const files = fs.readdirSync(cacheDir).filter(f => f.endsWith('.mp3'))
  files.forEach(f => fs.unlinkSync(path.join(cacheDir, f)))
  return { success: true, cleared: files.length }
})

function getYtDlpPath(): string {
  if (!app.isPackaged) {
    return path.join(app.getAppPath(), 'bin', 'yt-dlp.exe')
  }
  return path.join(process.resourcesPath, 'bin', 'yt-dlp.exe')
}

function ytDlpJson(args: string[]): Promise<any> {
  return new Promise((resolve, reject) => {
    const proc = spawn(getYtDlpPath(), args, { timeout: 30000 })
    let stdout = ''
    let stderr = ''
    proc.stdout.on('data', (d: Buffer) => (stdout += d.toString()))
    proc.stderr.on('data', (d: Buffer) => (stderr += d.toString()))
    proc.on('error', reject)
    proc.on('close', (code) => {
      if (code === 0) try { resolve(JSON.parse(stdout)) } catch { reject(new Error('JSON ayrıştırma hatası')) }
      else reject(new Error(stderr.trim() || `yt-dlp çıkış kodu: ${code}`))
    })
  })
}

function ytDlpBinary(args: string[]): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const proc = spawn(getYtDlpPath(), args, { timeout: 120000 })
    const chunks: Buffer[] = []
    let stderr = ''
    proc.stdout.on('data', (d: Buffer) => chunks.push(d))
    proc.stderr.on('data', (d: Buffer) => (stderr += d.toString()))
    proc.on('error', reject)
    proc.on('close', (code) => {
      if (code === 0) resolve(Buffer.concat(chunks))
      else reject(new Error(stderr.trim() || `yt-dlp çıkış kodu: ${code}`))
    })
  })
}

ipcMain.handle('youtube:get-audio', async (_e, videoId: string) => {
  const url = `https://www.youtube.com/watch?v=${videoId}`
  const info = await ytDlpJson(['--dump-json', '--no-warnings', '--no-playlist', url])
  const buffer = await ytDlpBinary([
    '-f', 'bestaudio',
    '--no-warnings',
    '--no-playlist',
    '--no-check-certificate',
    '-o', '-',
    url,
  ])

  return {
    buffer,
    title: info.title || 'Bilinmeyen Başlık',
    artist: info.uploader || info.channel || 'Bilinmeyen Sanatçı',
    duration: parseInt(info.duration) || 0,
    coverUrl: info.thumbnail || '',
    videoId,
  }
})