import { app, ipcMain } from 'electron'
import { autoUpdater } from 'electron-updater'
import path from 'path'
import fs from 'fs'
import { spawn } from 'child_process'
import { getMainWindow } from './window'

let downloadedUpdatePath: string | null = null
let isQuitting = false

export function isQuittingApp(): boolean {
  return isQuitting
}

export function markQuitting(): void {
  isQuitting = true
}

const isDev = !app.isPackaged

export function applyPortableUpdate() {
  const portableExe = process.env.PORTABLE_EXECUTABLE_FILE
  if (!portableExe || !downloadedUpdatePath || !fs.existsSync(downloadedUpdatePath)) return false
  try {
    const exeDir = path.dirname(portableExe)
    const exeName = path.basename(portableExe)
    const oldExe = path.join(exeDir, exeName)
    const oldExeBackup = path.join(exeDir, `${exeName}.bak`)
    const batPath = path.join(exeDir, `update-${Date.now()}.bat`)

    if (fs.existsSync(oldExeBackup)) fs.unlinkSync(oldExeBackup)
    fs.renameSync(oldExe, oldExeBackup)

    const batContent = `@echo off
:wait
tasklist /FI "PID eq ${process.pid}" 2>NUL | find /I /N "${process.pid}" >NUL
if not errorlevel 1 (
  timeout /t 1 /nobreak >NUL
  goto wait
)
copy /Y "${downloadedUpdatePath}" "${oldExe}" >NUL
start "" "${oldExe}"
del "%~f0"
`
    fs.writeFileSync(batPath, batContent)
    spawn(batPath, [], { detached: true, stdio: 'ignore', windowsHide: true }).unref()
    return true
  } catch (e) {
    console.error('[Update] portable replace error:', e)
    try {
      const oldExe = path.join(path.dirname(portableExe), path.basename(portableExe))
      const backup = oldExe + '.bak'
      if (fs.existsSync(backup) && !fs.existsSync(oldExe)) fs.renameSync(backup, oldExe)
    } catch {}
    return false
  }
}

export function setupUpdater() {
  autoUpdater.autoDownload = true
  autoUpdater.autoInstallOnAppQuit = true
  // electron-updater reads publish config from package.json (github provider)
  // latest.yml is generated by electron-builder automatically

  autoUpdater.on('checking-for-update', () => {
    getMainWindow()?.webContents.send('update:checking')
  })

  autoUpdater.on('update-available', (info) => {
    getMainWindow()?.webContents.send('update:available', info)
  })

  autoUpdater.on('update-not-available', () => {
    getMainWindow()?.webContents.send('update:not-available')
  })

  autoUpdater.on('download-progress', (progress) => {
    getMainWindow()?.webContents.send('update:progress', progress)
  })

  autoUpdater.on('update-downloaded', (info) => {
    try {
      const helper = (autoUpdater as any).downloadedUpdateHelper
      if (helper?.file) downloadedUpdatePath = helper.file
    } catch {}
    if (!downloadedUpdatePath && (info as any)?.downloadedFile) {
      downloadedUpdatePath = (info as any).downloadedFile
    }
    getMainWindow()?.webContents.send('update:downloaded')
  })

  autoUpdater.on('error', (err) => {
    if (isDev) return
    const msg = err.message || ''
    console.log('[AutoUpdate] Error:', msg)
    if (msg.includes('404') || msg.includes('ENOENT') || msg.includes('latest.yml')) {
      getMainWindow()?.webContents.send('update:not-available')
      return
    }
    getMainWindow()?.webContents.send('update:error', msg.includes('Cannot') || msg.includes('connect') ? 'Sunucuya bağlanılamadı' : msg.slice(0, 100))
  })

  ipcMain.handle('app:version', () => app.getVersion())

  ipcMain.on('update:check', () => {
    if (isDev) return
    autoUpdater.checkForUpdates()
  })

  ipcMain.on('update:download', () => {
    autoUpdater.downloadUpdate()
  })

  ipcMain.on('update:install', () => {
    if (applyPortableUpdate()) {
      app.quit()
      return
    }
    autoUpdater.quitAndInstall()
  })

  // Auto-install on quit for portable
  app.on('before-quit', (event) => {
    if (isQuitting) return
    if (!downloadedUpdatePath || !process.env.PORTABLE_EXECUTABLE_FILE) return
    isQuitting = true
    event.preventDefault()
    applyPortableUpdate()
    app.exit()
  })
}
